app:
  appName: "slack-bot"
  replicas: 1
  vaultUrl: https://vault-int.infra.cs-int-592.com
  vaultProject: slack-bot
  vaultNamespace: slack-bot
  nodeSelector:
    tier: "app"

  containerArgs: ["-text", "hello world"]

  statefulset:
    enabled: false

  deployment:
    enabled: true

  service:
    type: ClusterIP
    ports:
      http:
        externalPort: 80
        internalPort: 5678
        protocol: TCP

  image:
    repository: "278696104475.dkr.ecr.us-east-1.amazonaws.com/compstak/slack-bot"

  prometheus:
    enabled: false
    port: "8011"

  livenessProbe:
    enabled: false
    mode: httpGet
    httpGet:
      port: 5678
      path: "/health"

  readinessProbe:
    enabled: true
    mode: httpGet
    httpGet:
      port: 5678
      path: "/"

  job:
    enabled: false

#  configmap:
#    API_HOST: "exchange-api.compstak-services.svc.cluster.local"
#    API_PORT: 10020
#    PORT: 5251

   secrets:
     SQL_DATABASE: SQL_DATABASE

  extraSecrets:
    PG_SQL_HOST: vault:secret/data/infra/rds-postgress/{{ .Values.environment }}#RDS_HOST
    PG_SQL_PORT: vault:secret/data/infra/rds-postgress/{{ .Values.environment }}#RDS_PORT
    PG_SQL_USERNAME: vault:secret/data/infra/rds-postgress/{{ .Values.environment }}#RDS_USERNAME
    PG_SQL_PASSWORD: vault:secret/data/infra/rds-postgress/{{ .Values.environment }}#RDS_PASSWORD
    MY_SQL_HOST: vault:secret/data/infra/aurora-mysql-compstak-services/{{ .Values.environment }}#RDS_HOST
    MY_SQL_PORT: vault:secret/data/infra/aurora-mysql-compstak-services/{{ .Values.environment }}#RDS_PORT
    MY_SQL_USERNAME: vault:secret/data/infra/aurora-mysql-compstak-services/{{ .Values.environment }}#RDS_USERNAME
    MY_SQL_PASSWORD: vault:secret/data/infra/aurora-mysql-compstak-services/{{ .Values.environment }}#RDS_PASSWORD
    BOOTSTRAP_SERVERS: vault:secret/data/infra/msk/{{ .Values.environment }}#BOOTSTRAP_BROKERS
