app:
  environment: stage
  vaultAuthPath: kubernetes-stage


  image:
    tag: d2b1a0d10eba509e1476eafb0f5614b2124cd9a1

  resources:
    limits:
      memory: 16Mi
    requests:
      memory: 16Mi

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
      external-dns.alpha.kubernetes.io/hostname: slack-bot-int.stage.cs-int-592.com
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: argocd-internal-stage
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/success-codes: 200,204
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    hosts:
      - slack-bot-int.stage.cs-int-592.com
      - slack-bot.stage.cs-int-592.com
    paths:
      - path: /*
        backend:
          servicePort: 80
    extraPaths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
          
  serviceAccount:
    create: false
